baseURL = 'https://docs.rndll.io'
languageCode = 'en-us'
title = 'docs.rndll'
theme = 'hugo-book'

enableGitInfo = true
disableKinds = ['taxonomy','taxonomyTerm']

[params]
  BookTheme = 'dark'
  BookToc = false
  BookRepo = 'https://github.com/rpxio/docs'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main/'
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = true
  BookComments = false
